// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: learn2/test6_summary/proto/multi/multi.proto

package multi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Figure1 int64 `protobuf:"varint,1,opt,name=figure1,proto3" json:"figure1,omitempty"`
	Figure2 int64 `protobuf:"varint,2,opt,name=figure2,proto3" json:"figure2,omitempty"`
}

func (x *MultiRequest) Reset() {
	*x = MultiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_learn2_test6_summary_proto_multi_multi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRequest) ProtoMessage() {}

func (x *MultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learn2_test6_summary_proto_multi_multi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRequest.ProtoReflect.Descriptor instead.
func (*MultiRequest) Descriptor() ([]byte, []int) {
	return file_learn2_test6_summary_proto_multi_multi_proto_rawDescGZIP(), []int{0}
}

func (x *MultiRequest) GetFigure1() int64 {
	if x != nil {
		return x.Figure1
	}
	return 0
}

func (x *MultiRequest) GetFigure2() int64 {
	if x != nil {
		return x.Figure2
	}
	return 0
}

type MultiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res1 int64 `protobuf:"varint,1,opt,name=res1,proto3" json:"res1,omitempty"`
	Res2 int64 `protobuf:"varint,2,opt,name=res2,proto3" json:"res2,omitempty"`
}

func (x *MultiResponse) Reset() {
	*x = MultiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_learn2_test6_summary_proto_multi_multi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiResponse) ProtoMessage() {}

func (x *MultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_learn2_test6_summary_proto_multi_multi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiResponse.ProtoReflect.Descriptor instead.
func (*MultiResponse) Descriptor() ([]byte, []int) {
	return file_learn2_test6_summary_proto_multi_multi_proto_rawDescGZIP(), []int{1}
}

func (x *MultiResponse) GetRes1() int64 {
	if x != nil {
		return x.Res1
	}
	return 0
}

func (x *MultiResponse) GetRes2() int64 {
	if x != nil {
		return x.Res2
	}
	return 0
}

var File_learn2_test6_summary_proto_multi_multi_proto protoreflect.FileDescriptor

var file_learn2_test6_summary_proto_multi_multi_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x32, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x36, 0x5f, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x22, 0x42, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x31, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x32, 0x22, 0x37, 0x0a, 0x0d, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65,
	0x73, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65, 0x73, 0x31, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x65, 0x73, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x32, 0x32, 0x40, 0x0a, 0x05, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x12, 0x37, 0x0a, 0x08, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x12, 0x13, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x32, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x36, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_learn2_test6_summary_proto_multi_multi_proto_rawDescOnce sync.Once
	file_learn2_test6_summary_proto_multi_multi_proto_rawDescData = file_learn2_test6_summary_proto_multi_multi_proto_rawDesc
)

func file_learn2_test6_summary_proto_multi_multi_proto_rawDescGZIP() []byte {
	file_learn2_test6_summary_proto_multi_multi_proto_rawDescOnce.Do(func() {
		file_learn2_test6_summary_proto_multi_multi_proto_rawDescData = protoimpl.X.CompressGZIP(file_learn2_test6_summary_proto_multi_multi_proto_rawDescData)
	})
	return file_learn2_test6_summary_proto_multi_multi_proto_rawDescData
}

var file_learn2_test6_summary_proto_multi_multi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_learn2_test6_summary_proto_multi_multi_proto_goTypes = []interface{}{
	(*MultiRequest)(nil),  // 0: multi.MultiRequest
	(*MultiResponse)(nil), // 1: multi.MultiResponse
}
var file_learn2_test6_summary_proto_multi_multi_proto_depIdxs = []int32{
	0, // 0: multi.Multi.Multiply:input_type -> multi.MultiRequest
	1, // 1: multi.Multi.Multiply:output_type -> multi.MultiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_learn2_test6_summary_proto_multi_multi_proto_init() }
func file_learn2_test6_summary_proto_multi_multi_proto_init() {
	if File_learn2_test6_summary_proto_multi_multi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_learn2_test6_summary_proto_multi_multi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_learn2_test6_summary_proto_multi_multi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_learn2_test6_summary_proto_multi_multi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learn2_test6_summary_proto_multi_multi_proto_goTypes,
		DependencyIndexes: file_learn2_test6_summary_proto_multi_multi_proto_depIdxs,
		MessageInfos:      file_learn2_test6_summary_proto_multi_multi_proto_msgTypes,
	}.Build()
	File_learn2_test6_summary_proto_multi_multi_proto = out.File
	file_learn2_test6_summary_proto_multi_multi_proto_rawDesc = nil
	file_learn2_test6_summary_proto_multi_multi_proto_goTypes = nil
	file_learn2_test6_summary_proto_multi_multi_proto_depIdxs = nil
}
